export const CAR_OPTIONS = [
  {"name": "3-Row Seat", "key": "RS" },
  {"name": " A/C ", "key": "AC" },
  {"name": "ABS", "key": "ABS" },
  {"name": "Aero Parts", "key": "AP" },
  {"name": "Aftermarket Alloy Wheels", "key": "AAW" },
  {"name": "Aftermarket Meffler", "key": "AM" },
  {"name": "Aftermarket Speaker", "key": "AS" },
  {"name": "Airbag", "key": "A" },
  {"name": "Alloy Wheels", "key": "AW" },
  {"name": "Always Garaged", "key": "AG" },
  {"name": "AM/FM", "key": "AF" },
  {"name": "Anti-theft System", "key": "ATS" },
  {"name": "Around View Camera ", "key": "AVC" },
  {"name": "Audio System", "key": "AUS" },
  {"name": "Back Camera ", "key": "BC" },
  {"name": "Back Sensor ", "key": "BS" },
  {"name": "Back Tire", "key": "BT" },
  {"name": "Basic Equipment", "key": "BE" },
  {"name": "Bench Seat", "key": "BS" },
  {"name": "Body Kit", "key": "BK" },
  {"name": "Box Truck ", "key": "BTR" },
  {"name": "Bucket Seat", "key": "BKS" }
]

export const VEHICLE_DATA = [
	{"model":"ILX", "make": "Acura", "year": [2022]},
  {"model": "Integra", "make":"Acura", "year": [2024, 2023]},
  {"model": "MDX", "make": "Acura", "year": [2024, 2023, 2022]},
  {"model": "NSX", "make": "Acura", "year": [2022]},
  {"model": "RDX", "make": "Acura", "year": [2023, 2022]},
  {"model": "TLX", "make": "Acura", "year": [2023, 2022]},
  {"model": "ZDX", "make": "Acura", "year": [2024]},
  {"model": "Giulia", "make": "Alfa Romeo", "year": [2023, 2022]},
  {"model": "Stelvio", "make": "Alfa Romeo", "year": [2023, 2022]},
  {"model": "Tonale", "make": "Alfa Romeo", "year": [2024, 2023]},
  {"model": "DB11", "make": "Aston Martin", "year": [2023, 2022]},
  {"model": "DBS", "make": "Aston Martin", "year": [2023, 2022]},
  {"model": "DBX", "make": "Aston Martin", "year": [2024, 2023, 2022]},
  {"model": "Vantage", "make": "Aston Martin", "year": [2023, 2022]},
  {"model": "A3", "make":"Audi", "year": [2023, 2022]},
  {"model": "A4", "make": "Audi", "year": [2023, 2022]},
  {"model": "A4 allroad", "make": "Audi", "year": [2023, 2022]},
  {"model":"i4","make": "BMW", "year":[2023, 2022]},
  {"model": "i7", "make":"BMW","year": [2024, 2023]},
  {"model": "iX", "make": "BMW", "year": [2024, 2023]},
  {"model": "M2", "make": "BMW", "year": [2023]}

]

export const KENYA_LOCATION = [
  {"location":"Mombasa"},
{"location":"Kwale"},
{"location":"Kilifi"},
{"location":"Tana River"},
{"location":"Lamu"},
{"location":"Taita Mak Taveta"},
{"location":"Garissa"},
{"location":"Wajir"},
{"location":"Mandera"},
{"location":"Marsabit"},
{"location":"Isiolo"},
{"location":"Meru"},
{"location":"Tharaka-Nithi"},
{"location":"Embu"},
{"location":"Kitui"},
{"location":"Machakos"},
{"location":"Makueni"},
{"location":"Nyandarua"},
{"location":"Nyeri"},
{"location":"Kirinyaga"},
{"location":"Muranga"},
{"location":"Kiambu"},
{"location":"Turkana"},
{"location":"West Pokot"},
{"location":"Samburu"},
{"location":"Trans-Nzoia"},
{"location":"Uasin Gishu"},
{"location":"Elgeyo-Marakwet"},
{"location":"Nandi"},
{"location":"Baringo"},
{"location":"Laikipia"},
{"location":"Nakuru"},
{"location":"Narok"},
{"location":"Kajiado"},
{"location":"Kericho"},
{"location":"Bomet"},
{"location":"Kakamega"},
{"location":"Vihiga"},
{"location":"Bungoma"},
{"location":"Busia"},
{"location":"Siaya"},
{"location":"Kisumu"},
{"location":"Homa Bay"},
{"location":"Migori"},
{"location":"Kisii"},
{"location":"Nyamira"},
{"location":"Nairobi"},
]



